### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by imsnif** [imsnif/diskonaut#20]
Scanning large volumes with `diskonaut` takes some time. Not terrible (likely less than 10 minutes for really populated volumes) but this is still not the best experience.

It could be nice to experiment with scanning parallelization, as long as it does not impact performance. I feel a slow scan is better than a fast scan that makes your computer stuck and unable to do anything else.

**Comment by Byron** [comment]
I am the author of [dua](https://lib.rs/crates/dua-cli) and all I had to do for maximum performance is to use [jwalk](https://lib.rs/crates/jwalk) instead of walkdir. This completely hides away the parallelism behind an iterator of directory entries. What's even nicer is that a closure can run _on the thread_ to obtain, say, `metadata()`.

**Comment by JosephTLyons** [comment]
> I am the author of [dua](https://lib.rs/crates/dua-cli) and all I had to do for maximum performance is to use [jwalk](https://lib.rs/crates/jwalk) instead of walkdir. This completely hides away the parallelism behind an iterator of directory entries. What's even nicer is that a closure can run _on the thread_ to obtain, say, `metadata()`.

What sort of performance boosts did you see from using jwalk? I’m a contributor on a project that is facing a similar situation of wanting to switch to jwalk.

**Comment by Byron** [comment]
I think you can try it yourself by using `dua -t1` to limit it to a single thread, compared to `dua` that runs on as many threads as you have logical cores. For me it's between 3-4 times faster.

**Comment by imsnif** [comment]
Thanks for your input @Byron, jwalk looks really cool. I especially liked that it lets you limit parallelism: https://docs.rs/jwalk/0.5.1/jwalk/enum.Parallelism.html

My main concern here is to have it not take a lot of resources. Have you run into such issues with dua? (which looks really cool, btw)

**Comment by Byron** [comment]
The resources required to do things in parallel via jwalk are certainly dominated by the stacksize of each thread. It varies between operating systems, but is usually 512KB large at least. If this is an issue, the program will probably run out of space due to other factors first.

**Comment by imsnif** [comment]
That sounds very reasonable, actually. I'll experiment with jwalk in the next few days and report my findings. Thanks again for your input!

**Comment by imsnif** [comment]
I moved diskonaut to use jwalk instead of walkdir (https://github.com/imsnif/diskonaut/pull/38). For me it didn't shave off as much time (it was about 20% faster for a full scan if `/`), but I suppose it has a lot to do with caching and hardware differences.
In any case, I'm not seeing any performance hits or resource over-utilization. Very happy with the results. Thanks for the tip, @Byron!

**Comment by Byron** [comment]
Interesting! Assuming you are on an SSD and/or have enough RAM to allow the OS to fully cache the filesystem traversal after the first run, I would have expected way more than 20% of speedup.

This might hint at diskonaut to be CPU bound right now, and the processing of filesystem entries doesn't quite keep up with the parallel iterator.

Something that has potential for big speedups is to [put the meta-data fetching](https://github.com/imsnif/diskonaut/blob/6e449c6f243296b7e21b77206665bed1d400093b/src/main.rs#L153:L153) into the [parallel iterator state like dua does](https://github.com/Byron/dua-cli/blob/9156cf7cac8f91a496f7383940f3ce6140ffe54c/src/aggregate.rs#L35) (when configuring the iterator, this looks something [like this](https://github.com/Byron/dua-cli/blob/9156cf7cac8f91a496f7383940f3ce6140ffe54c/src/common.rs#L172). That way, the additional `lstat` call will be done in one of the rayon threads, instead of the single consumer thread.

**Comment by Byron** [comment]
Ah, and I just now read the edit - nonetheless, there might be additional speedup potential when fetching metadata using jwalk client state.
