### ISSUE TITLE
auto select single folder 

### ISSUE THREAD

**Issue by deathtrip** [imsnif/diskonaut#37]
When you enter a folder and there's only one subfolder, it makes sense to automatically select it.
Maybe also consider auto selecting the biggest folder if there are many subfolders.
Because currently it takes an extra button press to select anything.

**Comment by imsnif** [comment]
Hmm... I understand what you're saying, but I'm a little concerned about auto-selection for first-time users who don't yet "get" what the marked tile is. (If it appears because you did something as a user, I think you would immediately understand what it's for).

What would you think of instead of this, when going into a folder that just has 1 tile, we would automatically go into that tile's folder directly (recursively until we get to a folder with more than 1 rectangle)? So that if I'm in:
`/home/aram/` and I enter `/home/aram/something` which only has 1 folder called `data`, I would immediately get to `/home/aram/something/data`.

**Comment by deathtrip** [comment]
Going directly to a folder with more than one rectangle could also confuse some users.

Maybe then a command line switch or config file entry, so you could control both options.
You could for example have diskonaut select the biggest tile when there are many, and if there's only one, go down the folder hierarchy.

**Comment by imsnif** [comment]
I usually like avoiding command line switches to control behaviour unless it's an extreme circumstance (eg. text-only mode or something like that).

How about if we add a "hidden" feature, wherein if you press "ENTER" and nothing is selected, the app goes into the largest folder?

**Comment by deathtrip** [comment]
Seems like a good idea.
